CREATE TABLE account_balance (
    id INT PRIMARY KEY AUTO_INCREMENT,
    cash BIGINT UNSIGNED NOT NULL,
    equity BIGINT UNSIGNED NOT NULL,
    user_id VARCHAR(255),
    modified DATETIME(3) NOT NULL,
    
    FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
);