CREATE TABLE PortfolioMember (
    id INT PRIMARY KEY AUTO_INCREMENT,
    portfolioId INT,
    userId VARCHAR(255),
    contribution BIGINT UNSIGNED NOT NULL,
    earnings BIGINT UNSIGNED NOT NULL,
    created DATETIME(3) NOT NULL,
    FOREIGN KEY (portfolioId) REFERENCES Portfolio(id) ON DELETE CASCADE,
    FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);