# This workflow deploys the database schematic changes to a specified environment
name: deploy-changeset

on:
  push:
    branches: [ "sandbox", "development", "qa", "staging", "production" ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
      - name: Download dbcc from AWS S3
        run: aws s3 cp s3://theezy-app/dbcc.sh ./dbcc.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      - name: Create MySQL Login configuration
        run: mysql_config_editor set --login-path=${{ github.ref_name }} --user ${{ vars.MYSQL_USERNAME }} --host ${{ vars.MYSQL_HOSTNAME }}
      - name: Display MySQL Login configuration
        run: mysql_config_editor print --all
      - name: Run changesets
        run: bash dbcc.sh
        env:
          APP_DB: ${{ vars.MYSQL_DATABASE }}
          CHANGES_ENV: ${{ github.ref_name }}
          CHANGES_HOME: ${{ github.workspace }}
          CHANGES_FILE: changes.txt
          CHANGES_TABLE: theezy_trader
          LOGIN_PATH: ${{ github.event.ref }}
          MYSQL_PWD: ${{ secrets.MYSQL_PASSWORD }}
